name: Generate lists
on:
  push:
    branches: master
jobs:
  generate-lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Generate lists
        run: |
          sudo apt-get install xsltproc libxml2-utils
          for f in *.xml; do xmllint --format --output "$f" "$f"; done
          ./generate-lists.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate lists
